package pdfview

import (
	"app/internal/components"
	"app/internal/layout"
	"app/internal/model"
	"app/internal/pdftemplate"
	"app/pkg/reqcontext"
	"fmt"
	"net/url"

	g "maragu.dev/gomponents"
	h "maragu.dev/gomponents/html"
)

type PDFPageProps struct {
	Ctx              reqcontext.ReqContext
	Templates        []pdftemplate.RegisteredTemplate
	SelectedTemplate *pdftemplate.RegisteredTemplate
}

func PDFGeneratorPage(p PDFPageProps) g.Node {
	exampleJSON := ""
	selectedTemplateName := ""
	if p.SelectedTemplate != nil {
		exampleJSON = p.SelectedTemplate.ExampleJSON
		selectedTemplateName = p.SelectedTemplate.Name
	}

	header := h.Section(
		h.Class("pdf-generator-header"),
		h.Nav(
			h.Class("pdf-generator-nav"),
			h.A(
				h.Href("/pdf/logs"),
				g.Text("PDF generation logs"),
			),
		),
		h.H1(g.Text("PDF Templates")),
	)

	templatesList := h.Section(
		h.Class("templates-section"),
		h.H2(g.Text("Document templates")),
		h.P(g.Text("View available templates, inspect example inputs, and load them into the PDF tester.")),
		h.Div(
			h.Class("templates-grid"),
			g.Group(g.Map(p.Templates, func(t pdftemplate.RegisteredTemplate) g.Node {
				return h.Div(
					h.Class("template-card"),
					h.Div(
						h.Class("template-card-header"),
						h.H3(g.Text(t.Name)),
						g.If(t.Description != "", h.P(h.Class("template-card-description"), g.Text(t.Description))),
					),
					h.Div(
						h.Class("template-card-body"),
						h.Div(
							h.Class("template-card-actions"),
							h.A(
								h.Class("button primary small"),
								h.Href(fmt.Sprintf("?TemplateName=%s", url.QueryEscape(t.Name))),
								g.Text("Load into tester"),
							),
						),
					),
				)
			})),
		),
	)

	form := h.Form(
		h.Class("pdf-template-form"),
		h.Method("POST"),
		h.Target("_blank"),
		g.Group([]g.Node{
			h.H2(g.Text("Test a PDF template")),
			h.Label(
				g.Text("PDF Template Name"),
				h.Select(
					h.Name("TemplateName"),
					g.Attr("onchange", "handleTemplateNameChange(event)"),
					h.Option(h.Value(""), h.Disabled(), g.If(selectedTemplateName == "", h.Selected()), g.Text("Select a template to begin")),
					g.Group(g.Map(p.Templates, func(t pdftemplate.RegisteredTemplate) g.Node {
						return h.Option(
							h.Value(t.Name),
							g.If(selectedTemplateName == t.Name, h.Selected()),
							g.Text(t.Name),
						)
					})),
				),
			),
			h.Label(
				g.Text("Template Input Data (JSON)"),
				h.Textarea(
					h.Name("InputData"),
					g.Text(exampleJSON),
				),
			),
			g.If(exampleJSON != "", h.Div(
				h.Class("example-input"),
				g.Text("Example Input"),
				h.Pre(g.Text(exampleJSON)),
			)),
			h.Button(
				h.Class("button primary"),
				h.Type("submit"),
				g.Text("Generate PDF"),
			),
		}),
	)

	return layout.Page(layout.PageProps{
		Ctx:   p.Ctx,
		Title: "PDF Templates",
		Breadcrumbs: []layout.Breadcrumb{
			layout.HomeBreadcrumb,
			{
				IconIdentifier: "text-box-outline",
				Title:          "PDFs",
				URLPart:        "pdf",
			},
			{
				Title:   "PDF Templates",
				URLPart: "generate",
			},
		},
		Content: g.Group([]g.Node{
			header,
			templatesList,
			form,
		}),
		AppendHead: []g.Node{components.InlineStyle("/internal/views/pdfview/pdf_page.css")},
		AppendBody: []g.Node{components.InlineScript("/internal/views/pdfview/pdf_page.js")},
	})
}

func generationLogsSection(logs []model.PDFGenerationLog) g.Node {
	rows := components.TableRows{}
	for _, log := range logs {
		inputPreview := prettyJSON(log.InputData)
		documentCell := documentLinkCell(log.PDFTitle, log.FileURL)
		rows = append(rows, components.TableRow{
			Cells: []components.TableCell{
				{Contents: g.Text(log.TemplateName)},
				{Contents: documentCell},
				{Contents: h.Pre(h.Code(g.Text(inputPreview)))},
				{Contents: h.Pre(h.Code(g.Text(prettyJSON(log.PrintNodeOptions))))},
				{Contents: g.Text(log.CreatedByUsername)},
				{Contents: g.Text(log.CreatedAt.Format("2006-01-02 15:04:05"))},
			},
		})
	}

	return h.Section(
		h.Class("pdf-log-section"),
		h.H2(g.Text("Recent PDF generations")),
		components.Table(&components.TableProps{
			Columns: components.TableColumns{
				{TitleContents: g.Text("Template")},
				{TitleContents: g.Text("PDF title")},
				{TitleContents: g.Text("Input data")},
				{TitleContents: g.Text("Print options")},
				{TitleContents: g.Text("Generated by")},
				{TitleContents: g.Text("Generated at")},
			},
			Rows: rows,
		}),
	)
}
